server.port=8081

spring.datasource.url=jdbc:h2:mem:cardb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Stripe Configuration
stripe.api.key=${STRIPE_API_KEY:sk_test_placeholder}
