apiVersion: v1
kind: ConfigMap
metadata:
  name: car-rental-config
  namespace: car-rental
data:
  database.url: "jdbc:mysql://mysql-service:3306/cardb"
  jpa.ddl.auto: "create-drop"
  jwt.expiration: "86400000"
  logging.level: "DEBUG"
  spring.jpa.show-sql: "false"
