apiVersion: v1
kind: Service
metadata:
  name: car-rental-service
  namespace: car-rental
  labels:
    app: car-rental-app
spec:
  type: LoadBalancer
  selector:
    app: car-rental-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
