apiVersion: v1
kind: ServiceAccount
metadata:
  name: car-rental-sa
  namespace: car-rental
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: car-rental-role
  namespace: car-rental
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: car-rental-rolebinding
  namespace: car-rental
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: car-rental-role
subjects:
- kind: ServiceAccount
  name: car-rental-sa
  namespace: car-rental
